# Generated by Django 4.2.2 on 2023-07-04 10:03

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_image_file_data_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='file_data',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='Image', storage=django.core.files.storage.FileSystemStorage(location='path/to/your/image/folder'), upload_to='images/'),
        ),
    ]
