# Generated by Django 4.2.2 on 2023-07-04 10:06

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='Image', storage=django.core.files.storage.FileSystemStorage(location='/server/imageupload/Pictures/images'), upload_to='images/'),
        ),
    ]
